server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#############################新增网关配置###########################
  cloud:
    gateway:
      routes:
      - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        #配置动态路由，需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。
        #lb(注册中心中服务名字)方式,注意服务名中不能含有下划线
        uri: lb://cloud-payment-service #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/get/**         # 断言，路径相匹配的进行路由

      - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
        # 这个时间后才能起效
        #- After=2021-09-13T17:45:34.902+08:00[Asia/Shanghai]
        #- Cookie=chocolate, ch.p #curl http://localhost:9527/payment/lb --cookie "chocolate=chip"
        #- Header=X-Request-Id, \d+ #curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
####################################################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
