server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:sunlu123456/springcloud-config.git #GitHub上面的git仓库名字
          uri: https://github.com/sunlu123456/springcloud-config.git
          ####搜索目录
          search-paths:
          - springcloud-config
      ####读取分支
      label: master
  #rabbitmq相关配置<--------------------------
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
#什么是总线Bus
#在微服务架构的系统中，通常会使用轻量级的消息代理来构建一个共用的消息主题，并让系统中所有微服务实例都连接上来。
# 由于该主题中产生的消息会被所有实例监听和消费，所以称它为消息总线。
##rabbitmq相关配置,暴露bus刷新配置的端点，Bus动态刷新全局广播配置实现
#在cmd中输入以下命令
#全部通知
#curl -X POST "http://localhost:3344/actuator/bus-refresh"
#只通知3355，不通知3366
#curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355"
#config-client:3355（客户端服务名:端口）
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
