server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    ####consul注册中心地址
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

